// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCps1tKnxCbNj8bm_4ohomhagdU_MilKv0',
    appId: '1:392149948464:web:5697ebc1e25bc15ecaf5f5',
    messagingSenderId: '392149948464',
    projectId: 'dungeonsanddragons-f914e',
    authDomain: 'dungeonsanddragons-f914e.firebaseapp.com',
    storageBucket: 'dungeonsanddragons-f914e.firebasestorage.app',
    measurementId: 'G-KCF28WHJM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB1lGETUI2XZ5TGXLC1tGvkcE8SJmrjQg',
    appId: '1:392149948464:android:eac728e8bf746248caf5f5',
    messagingSenderId: '392149948464',
    projectId: 'dungeonsanddragons-f914e',
    storageBucket: 'dungeonsanddragons-f914e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmvQAjfhr-WCPsrgaJsw43y3JPeCnO-A',
    appId: '1:392149948464:ios:7710ec9220c33156caf5f5',
    messagingSenderId: '392149948464',
    projectId: 'dungeonsanddragons-f914e',
    storageBucket: 'dungeonsanddragons-f914e.firebasestorage.app',
    iosBundleId: 'com.example.dndApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmvQAjfhr-WCPsrgaJsw43y3JPeCnO-A',
    appId: '1:392149948464:ios:7710ec9220c33156caf5f5',
    messagingSenderId: '392149948464',
    projectId: 'dungeonsanddragons-f914e',
    storageBucket: 'dungeonsanddragons-f914e.firebasestorage.app',
    iosBundleId: 'com.example.dndApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCps1tKnxCbNj8bm_4ohomhagdU_MilKv0',
    appId: '1:392149948464:web:58a01b83badc2785caf5f5',
    messagingSenderId: '392149948464',
    projectId: 'dungeonsanddragons-f914e',
    authDomain: 'dungeonsanddragons-f914e.firebaseapp.com',
    storageBucket: 'dungeonsanddragons-f914e.firebasestorage.app',
    measurementId: 'G-NS3RL64T85',
  );
}
